version: "3.8"

services:
  ################################################################################
  # Kafka Setup - KRaft Mode
  ################################################################################
  # KRaft architecture with 3 Kafka brokers and 1 controller
  kafka-1:
    image: apache/kafka:3.8.0
    container_name: kafka-1
    ports:
      - "9092:9092"
      # All three brokers listen on 9092 inside their containers, but are exposed to your host on different ports (9092, 9093, 9094) so they don't conflict.
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker # handles data storage and client requests
      KAFKA_LISTENERS: PLAINTEXT://:9092 # broker listener
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092 # how clients connect to this broker
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # controller listener
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller:9093 # controller quorum configuration
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # disable auto topic creation
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3 # replication factor for internal topics
    networks:
      - kafka-net
    volumes:
      - kafka_1_data:/var/lib/kafka/data

  kafka-2:
    image: apache/kafka:3.8.0
    container_name: kafka-2
    ports:
      - "9093:9092" # 9093 on host maps to 9092 in container - second broker
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka-net
    volumes:
      - kafka_2_data:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:3.8.0
    container_name: kafka-3
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka-net
    volumes:
      - kafka_3_data:/var/lib/kafka/data

  kafka-controller:
    image: apache/kafka:3.8.0
    container_name: kafka-controller
    ports:
      - "19093:9093"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - kafka-net
    volumes:
      - kafka_controller_data:/var/lib/kafka/data

  kafka-setup:
    # Automatically create topics after Kafka brokers are up
    image: apache/kafka:3.8.0
    networks:
      - kafka-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    command: >
      sh -c "
      echo 'Waiting for Kafka...' &&
      sleep 30 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic transactions --bootstrap-server kafka-1:9092 --partitions 3 --replication-factor 3 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic fraud-alerts --bootstrap-server kafka-1:9092 --partitions 3 --replication-factor 3 &&
      echo 'Topic created'
      "

  ################################################################################
  # Application Producer
  ################################################################################
  app-producer-bank-a:
    build:
      context: .
      dockerfile: producers/Dockerfile
    environment:
      - KAFKA_BROKER=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - TOPIC=transactions
      - BANK_ID=BANK_A
      - USER_ID_MIN=1000
      - USER_ID_MAX=4999
      - TPS=50  # transactions per second
    networks:
      - kafka-net
    depends_on:
      kafka-setup:
        condition: service_completed_successfully

  app-producer-bank-b:
    build:
      context: .
      dockerfile: producers/Dockerfile
    environment:
      - KAFKA_BROKER=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - TOPIC=transactions
      - BANK_ID=BANK_B
      - USER_ID_MIN=5000
      - USER_ID_MAX=9999
      - TPS=30
    networks:
      - kafka-net
    depends_on:
      kafka-setup:
        condition: service_completed_successfully

  ################################################################################
  # Flink setup
  ################################################################################

  flink-jobmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 2
    networks:
      - kafka-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully

  flink-taskmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    depends_on:
      - flink-jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 6
        parallelism.default: 2
    networks:
      - kafka-net

  # Job Submitter
  flink-job-submitter:
    build:
      context: .
      dockerfile: flink/Dockerfile
    networks:
      - kafka-net
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
    command: >
      sh -c "
      echo 'Waiting for Flink to be ready...' &&
      sleep 60 &&
      /opt/flink/bin/sql-client.sh -f /opt/flink/jobs/flink_sql_job.sql &&
      echo 'Flink SQL job submitted successfully!'
      "
  ################################################################################
  # PostgreSQL Database
  ################################################################################
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: transactions_user
      POSTGRES_PASSWORD: transactions123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transactions_user -d transactions_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:
  kafka_controller_data:
  postgres_data:

networks:
  kafka-net:
    driver: bridge